name: Version Bump

on: workflow_dispatch

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - run: awk -i inplace '{sum = $1 + 1}; END {print sum}'  VERSION > VERSION.update && mv VERSION.update VERSION
        name: bump version

      - uses: stefanzweifel/git-auto-commit-action@v6