name: Version Bump

on: workflow_dispatch

jobs:
  format-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: 1413076
          private-key: ${{ secrets.BILLNAPIER_TEST_APP_PRIVATE_KEY }}


      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.generate-token.outputs.token }}

      - run: awk -i inplace '{sum = $1 + 1}; END {print sum}'  VERSION > VERSION.update && mv VERSION.update VERSION
        name: bump version

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Version Bump